# proyecto/pytest.ini
# Este archivo es clave en tu estructura.
# Le dice a pytest dónde buscar las pruebas y,
# muy importante,
# añade la carpeta src al path de Python para que 
# en los tests podamos hacer 
# from app import... sin que nos dé un error de
# módulo no encontrado.

[pytest]
testpaths = tests
pythonpath = src
addopts = -v

# addopts = -v ejecuta las pruebas en modo "verbose" para 
# ver  el nombre de cada prueba que ha pasado.
